package postgres

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/wsciaroni/opsdeck/internal/core/domain"
)

type UserRepository struct {
	db *pgxpool.Pool
}

func NewUserRepository(db *pgxpool.Pool) *UserRepository {
	return &UserRepository{db: db}
}

func (r *UserRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	query := `
		SELECT id, email, name, role, avatar_url, created_at, updated_at
		FROM users
		WHERE id = $1
	`
	row := r.db.QueryRow(ctx, query, id)

	var user domain.User
	var avatarURL *string // database allows null, we need to handle it properly if domain expects string
	// Wait, domain.User.AvatarURL is string. If DB is NULL, we should scan to sql.NullString or *string and convert.

	err := row.Scan(
		&user.ID,
		&user.Email,
		&user.Name,
		&user.Role,
		&avatarURL,
		&user.CreatedAt,
		&user.UpdatedAt,
	)

	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to get user by id: %w", err)
	}

	if avatarURL != nil {
		user.AvatarURL = *avatarURL
	}

	return &user, nil
}

func (r *UserRepository) GetByIDs(ctx context.Context, ids []uuid.UUID) ([]domain.User, error) {
	if len(ids) == 0 {
		return []domain.User{}, nil
	}

	query := `
		SELECT id, email, name, role, avatar_url, created_at, updated_at
		FROM users
		WHERE id = ANY($1)
	`
	rows, err := r.db.Query(ctx, query, ids)
	if err != nil {
		return nil, fmt.Errorf("failed to get users by ids: %w", err)
	}
	defer rows.Close()

	var users []domain.User
	for rows.Next() {
		var user domain.User
		var avatarURL *string

		err := rows.Scan(
			&user.ID,
			&user.Email,
			&user.Name,
			&user.Role,
			&avatarURL,
			&user.CreatedAt,
			&user.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan user: %w", err)
		}

		if avatarURL != nil {
			user.AvatarURL = *avatarURL
		}
		users = append(users, user)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("rows iteration error: %w", err)
	}

	return users, nil
}

func (r *UserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	query := `
		SELECT id, email, name, role, avatar_url, created_at, updated_at
		FROM users
		WHERE email = $1
	`
	row := r.db.QueryRow(ctx, query, email)

	var user domain.User
	var avatarURL *string

	err := row.Scan(
		&user.ID,
		&user.Email,
		&user.Name,
		&user.Role,
		&avatarURL,
		&user.CreatedAt,
		&user.UpdatedAt,
	)

	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to get user by email: %w", err)
	}

	if avatarURL != nil {
		user.AvatarURL = *avatarURL
	}

	return &user, nil
}

func (r *UserRepository) Create(ctx context.Context, user *domain.User) error {
	query := `
		INSERT INTO users (email, name, role, avatar_url)
		VALUES ($1, $2, $3, $4)
		RETURNING id, created_at, updated_at
	`
	// If user.AvatarURL is empty string, do we insert NULL or empty string?
	// The table allows NULL. Domain model has string. Empty string is valid.
	// But let's assume empty string in domain means NULL in DB or empty string.
	// DB definition: avatar_url TEXT.
	// Let's pass it as is.

	// Also, if user.ID is set, we might want to respect it?
	// The prompt said: "In SQL, use DEFAULT gen_random_uuid(). In Go Create(), use the RETURNING id clause to ensure the struct has the correct ID after insertion (whether generated by Go or DB)."
	// If I insert without ID, DB generates it.
	// If the user struct HAS an ID, I should probably use it if I want to support client-side IDs?
	// But usually, if ID is empty/zero, we let DB generate.
	// The SQL says `id UUID PRIMARY KEY DEFAULT gen_random_uuid()`.
	// If I don't include ID in INSERT list, it uses default.
	// If I want to allow setting ID, I should include it.
	// The requirements didn't explicitly say "allow providing ID".
	// "In Go Create(), use the RETURNING id clause to ensure the struct has the correct ID after insertion".
	// I will stick to letting DB generate it for now, as that's safer and implied by "DEFAULT gen_random_uuid()".
	// Wait, if I want to support pre-generated IDs (e.g. for idempotency or testing), I should check if user.ID is not zero.
	// But `gen_random_uuid` default implies we want the DB to do it usually.
	// I will just insert email, name, role, avatar_url.

	var avatarURL *string
	if user.AvatarURL != "" {
		avatarURL = &user.AvatarURL
	}

	err := r.db.QueryRow(ctx, query, user.Email, user.Name, user.Role, avatarURL).Scan(&user.ID, &user.CreatedAt, &user.UpdatedAt)
	if err != nil {
		return fmt.Errorf("failed to create user: %w", err)
	}

	return nil
}

func (r *UserRepository) Update(ctx context.Context, user *domain.User) error {
	query := `
		UPDATE users
		SET name = $1, role = $2, avatar_url = $3, updated_at = NOW()
		WHERE id = $4
		RETURNING updated_at
	`

	var avatarURL *string
	if user.AvatarURL != "" {
		avatarURL = &user.AvatarURL
	}

	err := r.db.QueryRow(ctx, query, user.Name, user.Role, avatarURL, user.ID).Scan(&user.UpdatedAt)
	if err != nil {
		return fmt.Errorf("failed to update user: %w", err)
	}
	// Note: If no rows updated (id not found), Scan might return ErrNoRows?
	// UPDATE ... RETURNING returns rows only if updated.
	// If id does not exist, it returns 0 rows. Scan will return ErrNoRows.
	// This effectively acts as "ensure user exists".

	return nil
}
