ALTER TABLE tickets ADD COLUMN sensitive BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE comments ADD COLUMN sensitive BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE tickets ALTER COLUMN sensitive SET DEFAULT FALSE;
ALTER TABLE comments ALTER COLUMN sensitive SET DEFAULT FALSE;
